import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AnamanaguchiExams.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Anamanaguchi <a>EXAMS!</a>
        </h1>

        <p className={styles.description}>
            Welcome!
        </p>

        <div>
            <h2>Usernaname</h2>
            <input placeholder="anamanaguchi"></input>

            <h2>Password</h2>
            <input type="password" placeholder="1234"></input>
        </div> 

        <div>
          <a
            href="home"
          >
            <h2>log in &rarr;</h2>
          </a>
        </div>

        <div >
          <a
            href="signUp"
          >
            <h2>Sign Up &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
